# Generated by Django 5.1.5 on 2025-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsitting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="lgt",
            field=models.FloatField(default=-0.09),
        ),
        migrations.AddField(
            model_name="plant",
            name="ltn",
            field=models.FloatField(default=51.5),
        ),
    ]
